services:
  - type: web
    name: n8n
    runtime: docker
    dockerCommand: n8n start
    dockerImage: n8nio/n8n
    plan: free
    envVars:
      - key: N8N_HOST
        sync: false
      - key: N8N_PORT
        value: 10000
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: WEBHOOK_URL
        sync: false
      - key: GENERIC_TIMEZONE
        value: Asia/Bangkok
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
